export const admissionsSources = [
  {
    id: "adiga",
    name: "대입정보포털 어디가",
    url: "https://www.adiga.kr/",
    note:
      "대교협이 운영하는 공식 대입정보 포털입니다. 대학/학과/전형정보, 학생부 성적분석, 전년도 입시결과를 조회할 수 있습니다.",
  },
  {
    id: "kcue",
    name: "한국대학교육협의회 2026학년도 대학입학전형기본사항",
    url: "https://www.kcue.or.kr/news/sub02/sub01.php?at=view&idx=24138",
    note:
      "대학은 모집단위별 전형요소 반영비율, 학생부 반영교과와 반영방법 등을 대학입학전형시행계획에 공표해야 합니다.",
  },
  {
    id: "kyungnam-2026",
    name: "경남대학교 2026학년도 수시모집요강",
    url:
      "https://ipsi.kyungnam.ac.kr/sites/ipsi/down/2026%ED%95%99%EB%85%84%EB%8F%84_%EC%88%98%EC%8B%9C%EB%AA%A8%EC%A7%91%EC%9A%94%EA%B0%95.pdf",
    note:
      "물리치료학과 학생부교과 전형의 학생부 100%(교과 90% + 출결 10%) 및 수능최저 적용 여부를 확인했습니다.",
  },
  {
    id: "dongsin-pt",
    name: "동신대학교 물리치료학과 입학정보",
    url: "https://cess.dsu.ac.kr/dspt/index.php?pCode=MN7000043",
    note:
      "물리치료학과 학생부 교과 80% + 출결 20%, 국어/영어/수학/과학/사회/한국사 전과목 반영 방식을 확인했습니다.",
  },
  {
    id: "knsu-2026",
    name: "한국체육대학교 2026학년도 수시모집요강 공지",
    url:
      "https://www.knsu.ac.kr/ipsi/rolling/application.do?articleNo=53938&mode=view&title=2026%ED%95%99%EB%85%84%EB%8F%84+%EC%88%98%EC%8B%9C%EB%AA%A8%EC%A7%91%EC%9A%94%EA%B0%95+%EC%88%98%EC%A0%95+%EC%95%8C%EB%A6%BC%28%EC%B2%B4%EC%9C%A1%ED%8A%B9%EA%B8%B0%EC%9E%90+%EA%B5%AD%EA%B0%80%EB%8C%80%ED%91%9C+%EB%B0%8F+%ED%9B%84%EB%B3%B4%EC%84%A0%EC%88%98+%EC%84%B8%EB%B6%80%EC%A2%85%EB%AA%A9+%ED%99%95%EC%9D%B8%EC%84%9C+%EC%84%9C%EC%8B%9D+%EC%B6%94%EA%B0%80%29",
    note:
      "체육계열은 실기/특기자/교과 전형별 변경 공지가 잦으므로 최종 모집요강 확인이 필요합니다.",
  },
];

export const subjectLabels = {
  korean: "국어",
  math: "수학",
  english: "영어",
  social: "사회/한국사",
  science: "과학",
  pe: "체육/예술",
  overall: "전체 평균",
};

const naturalScienceWeights = {
  korean: 18,
  math: 24,
  english: 24,
  social: 10,
  science: 24,
};

const broadSubjectWeights = {
  korean: 20,
  math: 20,
  english: 25,
  social: 20,
  science: 15,
};

const physicalEducationWeights = {
  korean: 20,
  math: 10,
  english: 30,
  social: 25,
  pe: 15,
};

const practicalHeavyWeights = {
  korean: 15,
  english: 35,
  social: 25,
  pe: 25,
};

export const admissionPrograms = [
  {
    id: "kyungnam-pt-general",
    university: "경남대학교",
    department: "물리치료학과",
    region: "경남",
    field: "physical_therapy",
    track: "학생부교과 일반/지역인재 계열",
    officialUrl:
      "https://ipsi.kyungnam.ac.kr/sites/ipsi/down/2026%ED%95%99%EB%85%84%EB%8F%84_%EC%88%98%EC%8B%9C%EB%AA%A8%EC%A7%91%EC%9A%94%EA%B0%95.pdf",
    sourceRefs: ["adiga", "kcue", "kyungnam-2026"],
    dataQuality: "2026 반영비율 확인, 2024~2025 기준선은 모의 보정값",
    note:
      "2026 모집요강에서 학생부 100%(교과 90% + 출결 10%)와 물리치료학과 수능최저 적용을 확인했습니다.",
    years: {
      2026: {
        record: 90,
        attendance: 10,
        practical: 0,
        interview: 0,
        subjectWeights: naturalScienceWeights,
        benchmarkGrade: 3.05,
        resultStatus: "모집요강 기반 목표선",
        minRequirement: "수능최저 적용 가능성 높음",
      },
      2025: {
        record: 90,
        attendance: 10,
        practical: 0,
        interview: 0,
        subjectWeights: naturalScienceWeights,
        benchmarkGrade: 3.18,
        resultStatus: "전년도 결과 확인 필요",
        minRequirement: "입학처/어디가 확인",
      },
      2024: {
        record: 90,
        attendance: 10,
        practical: 0,
        interview: 0,
        subjectWeights: naturalScienceWeights,
        benchmarkGrade: 3.27,
        resultStatus: "전년도 결과 확인 필요",
        minRequirement: "입학처/어디가 확인",
      },
    },
  },
  {
    id: "dongsin-pt-general",
    university: "동신대학교",
    department: "물리치료학과",
    region: "전남",
    field: "physical_therapy",
    track: "일반/지역학생 학생부교과",
    officialUrl: "https://cess.dsu.ac.kr/dspt/index.php?pCode=MN7000043",
    sourceRefs: ["adiga", "dongsin-pt"],
    dataQuality: "2026 반영비율 확인, 2024~2025 기준선은 모의 보정값",
    note:
      "학과 입학정보에서 학생부 교과 80% + 출결 20%, 반영교과 전과목, 이수단위/진로선택 가산점을 확인했습니다.",
    years: {
      2026: {
        record: 80,
        attendance: 20,
        practical: 0,
        interview: 0,
        subjectWeights: broadSubjectWeights,
        benchmarkGrade: 3.55,
        resultStatus: "모집요강 기반 목표선",
        minRequirement: "전형별 최저/가산점 확인",
      },
      2025: {
        record: 80,
        attendance: 20,
        practical: 0,
        interview: 0,
        subjectWeights: broadSubjectWeights,
        benchmarkGrade: 3.68,
        resultStatus: "전년도 결과 확인 필요",
        minRequirement: "입학처/어디가 확인",
      },
      2024: {
        record: 80,
        attendance: 20,
        practical: 0,
        interview: 0,
        subjectWeights: broadSubjectWeights,
        benchmarkGrade: 3.82,
        resultStatus: "전년도 결과 확인 필요",
        minRequirement: "입학처/어디가 확인",
      },
    },
  },
  {
    id: "gachon-pt-student",
    university: "가천대학교",
    department: "물리치료학과",
    region: "경기",
    field: "physical_therapy",
    track: "학생부교과/지역균형 유사 전형",
    officialUrl: "https://www.adiga.kr/",
    sourceRefs: ["adiga", "kcue"],
    dataQuality: "관심대학 비교용 모의 데이터",
    note:
      "수도권 물리치료학과는 교과 환산식과 수능최저 영향이 큰 편이라 공식 환산점수 확인이 필수입니다.",
    years: {
      2026: {
        record: 100,
        attendance: 0,
        practical: 0,
        interview: 0,
        subjectWeights: naturalScienceWeights,
        benchmarkGrade: 2.35,
        resultStatus: "모집요강 확인 필요",
        minRequirement: "전형별 수능최저 확인",
      },
      2025: {
        record: 100,
        attendance: 0,
        practical: 0,
        interview: 0,
        subjectWeights: naturalScienceWeights,
        benchmarkGrade: 2.47,
        resultStatus: "어디가/입학처 확인 필요",
        minRequirement: "전형별 수능최저 확인",
      },
      2024: {
        record: 100,
        attendance: 0,
        practical: 0,
        interview: 0,
        subjectWeights: naturalScienceWeights,
        benchmarkGrade: 2.58,
        resultStatus: "어디가/입학처 확인 필요",
        minRequirement: "전형별 수능최저 확인",
      },
    },
  },
  {
    id: "sahmyook-pt-student",
    university: "삼육대학교",
    department: "물리치료학과",
    region: "서울",
    field: "physical_therapy",
    track: "학생부교과 유사 전형",
    officialUrl: "https://www.adiga.kr/",
    sourceRefs: ["adiga", "kcue"],
    dataQuality: "관심대학 비교용 모의 데이터",
    note:
      "수도권 보건계열은 면접/서류/수능최저 조합이 전형별로 달라질 수 있어 전형명 단위 확인이 필요합니다.",
    years: {
      2026: {
        record: 100,
        attendance: 0,
        practical: 0,
        interview: 0,
        subjectWeights: naturalScienceWeights,
        benchmarkGrade: 2.22,
        resultStatus: "모집요강 확인 필요",
        minRequirement: "전형별 수능최저 확인",
      },
      2025: {
        record: 100,
        attendance: 0,
        practical: 0,
        interview: 0,
        subjectWeights: naturalScienceWeights,
        benchmarkGrade: 2.34,
        resultStatus: "어디가/입학처 확인 필요",
        minRequirement: "전형별 수능최저 확인",
      },
      2024: {
        record: 100,
        attendance: 0,
        practical: 0,
        interview: 0,
        subjectWeights: naturalScienceWeights,
        benchmarkGrade: 2.45,
        resultStatus: "어디가/입학처 확인 필요",
        minRequirement: "전형별 수능최저 확인",
      },
    },
  },
  {
    id: "knsu-sport-performance",
    university: "한국체육대학교",
    department: "체육계열/운동건강 관련 모집단위",
    region: "서울",
    field: "physical_education",
    track: "실기/실적 중심 전형",
    officialUrl:
      "https://www.knsu.ac.kr/ipsi/rolling/application.do?articleNo=53938&mode=view&title=2026%ED%95%99%EB%85%84%EB%8F%84+%EC%88%98%EC%8B%9C%EB%AA%A8%EC%A7%91%EC%9A%94%EA%B0%95+%EC%88%98%EC%A0%95+%EC%95%8C%EB%A6%BC%28%EC%B2%B4%EC%9C%A1%ED%8A%B9%EA%B8%B0%EC%9E%90+%EA%B5%AD%EA%B0%80%EB%8C%80%ED%91%9C+%EB%B0%8F+%ED%9B%84%EB%B3%B4%EC%84%A0%EC%88%98+%EC%84%B8%EB%B6%80%EC%A2%85%EB%AA%A9+%ED%99%95%EC%9D%B8%EC%84%9C+%EC%84%9C%EC%8B%9D+%EC%B6%94%EA%B0%80%29",
    sourceRefs: ["adiga", "knsu-2026"],
    dataQuality: "체육계열 전형 변경 가능성 높음",
    note:
      "체육계열은 종목/실기/입상실적 요건이 당락에 크게 작용합니다. 지원 전 반드시 최신 수정 모집요강을 확인하세요.",
    years: {
      2026: {
        record: 35,
        attendance: 5,
        practical: 50,
        interview: 10,
        subjectWeights: practicalHeavyWeights,
        benchmarkGrade: 4.05,
        resultStatus: "모집요강 기반 목표선",
        minRequirement: "종목별 실기/실적 요건 확인",
      },
      2025: {
        record: 35,
        attendance: 5,
        practical: 50,
        interview: 10,
        subjectWeights: practicalHeavyWeights,
        benchmarkGrade: 4.18,
        resultStatus: "전년도 결과 확인 필요",
        minRequirement: "종목별 실기/실적 요건 확인",
      },
      2024: {
        record: 35,
        attendance: 5,
        practical: 50,
        interview: 10,
        subjectWeights: practicalHeavyWeights,
        benchmarkGrade: 4.35,
        resultStatus: "전년도 결과 확인 필요",
        minRequirement: "종목별 실기/실적 요건 확인",
      },
    },
  },
  {
    id: "yongin-sports",
    university: "용인대학교",
    department: "스포츠/체육 관련 학과",
    region: "경기",
    field: "physical_education",
    track: "학생부 + 실기 유사 전형",
    officialUrl: "https://www.adiga.kr/",
    sourceRefs: ["adiga", "kcue"],
    dataQuality: "관심대학 비교용 모의 데이터",
    note:
      "체육 실기 반영 비중이 큰 대학은 내신보다 실기 백분위 개선 효과가 클 수 있습니다.",
    years: {
      2026: {
        record: 40,
        attendance: 0,
        practical: 60,
        interview: 0,
        subjectWeights: physicalEducationWeights,
        benchmarkGrade: 4.45,
        resultStatus: "모집요강 확인 필요",
        minRequirement: "실기 종목/기준표 확인",
      },
      2025: {
        record: 40,
        attendance: 0,
        practical: 60,
        interview: 0,
        subjectWeights: physicalEducationWeights,
        benchmarkGrade: 4.58,
        resultStatus: "어디가/입학처 확인 필요",
        minRequirement: "실기 종목/기준표 확인",
      },
      2024: {
        record: 40,
        attendance: 0,
        practical: 60,
        interview: 0,
        subjectWeights: physicalEducationWeights,
        benchmarkGrade: 4.72,
        resultStatus: "어디가/입학처 확인 필요",
        minRequirement: "실기 종목/기준표 확인",
      },
    },
  },
  {
    id: "kyunghee-sports-medicine",
    university: "경희대학교",
    department: "스포츠의학/체육 관련 모집단위",
    region: "경기",
    field: "physical_education",
    track: "학생부종합/실기 혼합 검토",
    officialUrl: "https://www.adiga.kr/",
    sourceRefs: ["adiga", "kcue"],
    dataQuality: "관심대학 비교용 모의 데이터",
    note:
      "학생부종합 성격이 강한 전형은 내신 등급만으로 합격 가능성을 단정하기 어렵습니다. 활동/세특/면접 평가를 별도로 봐야 합니다.",
    years: {
      2026: {
        record: 60,
        attendance: 0,
        practical: 20,
        interview: 20,
        subjectWeights: broadSubjectWeights,
        benchmarkGrade: 2.75,
        resultStatus: "모집요강 확인 필요",
        minRequirement: "서류/면접 평가기준 확인",
      },
      2025: {
        record: 60,
        attendance: 0,
        practical: 20,
        interview: 20,
        subjectWeights: broadSubjectWeights,
        benchmarkGrade: 2.86,
        resultStatus: "어디가/입학처 확인 필요",
        minRequirement: "서류/면접 평가기준 확인",
      },
      2024: {
        record: 60,
        attendance: 0,
        practical: 20,
        interview: 20,
        subjectWeights: broadSubjectWeights,
        benchmarkGrade: 2.98,
        resultStatus: "어디가/입학처 확인 필요",
        minRequirement: "서류/면접 평가기준 확인",
      },
    },
  },
  {
    id: "incheon-sports-science",
    university: "인천대학교",
    department: "스포츠과학/체육교육 관련 모집단위",
    region: "인천",
    field: "physical_education",
    track: "학생부교과 + 실기 유사 전형",
    officialUrl: "https://www.adiga.kr/",
    sourceRefs: ["adiga", "kcue"],
    dataQuality: "관심대학 비교용 모의 데이터",
    note:
      "교과군별 반영비율이 모집단위마다 달라질 수 있어 국어/영어/사회/과학 중 유리한 조합 확인이 필요합니다.",
    years: {
      2026: {
        record: 55,
        attendance: 0,
        practical: 45,
        interview: 0,
        subjectWeights: physicalEducationWeights,
        benchmarkGrade: 3.72,
        resultStatus: "모집요강 확인 필요",
        minRequirement: "실기 기준표 확인",
      },
      2025: {
        record: 55,
        attendance: 0,
        practical: 45,
        interview: 0,
        subjectWeights: physicalEducationWeights,
        benchmarkGrade: 3.86,
        resultStatus: "어디가/입학처 확인 필요",
        minRequirement: "실기 기준표 확인",
      },
      2024: {
        record: 55,
        attendance: 0,
        practical: 45,
        interview: 0,
        subjectWeights: physicalEducationWeights,
        benchmarkGrade: 4.02,
        resultStatus: "어디가/입학처 확인 필요",
        minRequirement: "실기 기준표 확인",
      },
    },
  },
];
